#!/usr/bin/env bash
# ----------------------------------------------------------------------
# Bulk-create the 10 Trade Copilot uptime monitors on BetterUptime.
#
# Prereqs:
#   1. Account at https://betterstack.com/better-uptime (free tier OK)
#   2. Personal access token: Account Settings → API → Generate token
#   3. Export it before running:   export BETTERUPTIME_TOKEN='betteruptime_xxx'
#
# Usage:
#   bash scripts/setup_betteruptime.sh                # create all 10 monitors
#   bash scripts/setup_betteruptime.sh --dry-run      # print the curls without firing
#
# The script is idempotent-ish — re-running creates duplicates, so check
# the dashboard first if you want to re-run. To delete a monitor, hit the
# X in the UI; the API endpoint is documented at:
#   https://docs.betterstack.com/uptime/api/list-monitors/
# ----------------------------------------------------------------------
set -euo pipefail

DRY_RUN=0
if [[ "${1-}" == "--dry-run" ]]; then DRY_RUN=1; fi

if [[ -z "${BETTERUPTIME_TOKEN-}" && "$DRY_RUN" -eq 0 ]]; then
  echo "BETTERUPTIME_TOKEN env var not set — export it and re-run." >&2
  echo "Get one at: https://uptime.betterstack.com/team/<your-team>/api-tokens" >&2
  exit 1
fi

API="https://uptime.betterstack.com/api/v2/monitors"
AUTH="Authorization: Bearer ${BETTERUPTIME_TOKEN-DRY-RUN-TOKEN}"
CT="Content-Type: application/json"

# Helper — POST a monitor; in dry-run mode just print the body.
create_monitor() {
  local name="$1"
  local body="$2"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '\n>>> %s\n%s\n' "$name" "$body"
    return
  fi
  echo "creating: $name"
  curl -sS -X POST "$API" -H "$AUTH" -H "$CT" -d "$body" \
    | python3 -c 'import sys, json; r = json.load(sys.stdin); print("  id:", r.get("data",{}).get("id"), "·", r.get("data",{}).get("attributes",{}).get("url"))'
}

# 1. Backend liveness
create_monitor "backend /health" '{
  "monitor_type": "expected_status_code",
  "url": "https://trade-copilot-api.fly.dev/health",
  "pronounceable_name": "Trade Copilot Backend",
  "expected_status_codes": [200],
  "check_frequency": 180,
  "request_timeout": 8,
  "regions": ["us", "eu"]
}'

# 2. Backend deep health with keyword (DB reachable)
create_monitor "backend /health/detail · DB ok" '{
  "monitor_type": "keyword",
  "url": "https://trade-copilot-api.fly.dev/health/detail",
  "pronounceable_name": "TC Backend DB Probe",
  "required_keyword": "\"database\":{\"status\":\"ok\"",
  "check_frequency": 300,
  "request_timeout": 10,
  "regions": ["us"]
}'

# 3. Backend deep health · TradeLocker reachable
create_monitor "backend /health/detail · broker ok" '{
  "monitor_type": "keyword",
  "url": "https://trade-copilot-api.fly.dev/health/detail",
  "pronounceable_name": "TC TradeLocker Probe",
  "required_keyword": "\"tradelocker_demo\":{\"status\":\"ok\"",
  "check_frequency": 300,
  "request_timeout": 10,
  "regions": ["us"]
}'

# 4. Frontend
create_monitor "frontend trading.jetlag-recovery.com" '{
  "monitor_type": "expected_status_code",
  "url": "https://trading.jetlag-recovery.com/",
  "pronounceable_name": "Trade Copilot Frontend",
  "expected_status_codes": [200],
  "check_frequency": 300,
  "request_timeout": 8,
  "regions": ["us"]
}'

# 5. Staging backend
create_monitor "staging backend /health" '{
  "monitor_type": "expected_status_code",
  "url": "https://trade-copilot-api-staging.fly.dev/health",
  "pronounceable_name": "TC Staging",
  "expected_status_codes": [200],
  "check_frequency": 600,
  "request_timeout": 8,
  "regions": ["us"]
}'

# 6. LaT-PFN inference service on DO VM
create_monitor "latpfn-inference 159.203.138.96:8765" '{
  "monitor_type": "keyword",
  "url": "http://159.203.138.96:8765/health",
  "pronounceable_name": "LaT-PFN Inference",
  "required_keyword": "\"status\":\"ok\"",
  "check_frequency": 300,
  "request_timeout": 10,
  "regions": ["us"]
}'

# 7. Backend SSL cert
create_monitor "SSL cert backend" '{
  "monitor_type": "ssl_cert",
  "url": "https://trade-copilot-api.fly.dev/",
  "pronounceable_name": "TC Backend SSL",
  "check_frequency": 86400,
  "remind_when_certificate_expires_in": 14
}'

# 8. Frontend SSL cert
create_monitor "SSL cert frontend" '{
  "monitor_type": "ssl_cert",
  "url": "https://trading.jetlag-recovery.com/",
  "pronounceable_name": "TC Frontend SSL",
  "check_frequency": 86400,
  "remind_when_certificate_expires_in": 14
}'

# 9. Cron heartbeat: daily summary (the backend task hits this URL once /day)
# This monitor's URL is generated BY BetterUptime when you create it;
# stub it as "expected_status_code" against /health for now and switch to
# a heartbeat monitor in the UI once you copy the heartbeat URL.
create_monitor "cron · daily summary heartbeat (placeholder)" '{
  "monitor_type": "expected_status_code",
  "url": "https://trade-copilot-api.fly.dev/health",
  "pronounceable_name": "Daily Summary Cron",
  "expected_status_codes": [200],
  "check_frequency": 86400,
  "request_timeout": 5
}'

# 10. Cron heartbeat: SQLite backup
create_monitor "cron · backup heartbeat (placeholder)" '{
  "monitor_type": "expected_status_code",
  "url": "https://trade-copilot-api.fly.dev/health",
  "pronounceable_name": "Backup Cron",
  "expected_status_codes": [200],
  "check_frequency": 86400,
  "request_timeout": 5
}'

if [[ "$DRY_RUN" -eq 0 ]]; then
  echo
  echo "Done. Visit your dashboard at:"
  echo "  https://uptime.betterstack.com/team/<your-team>/monitors"
  echo
  echo "Next: for monitors 9 + 10, switch the 'monitor type' to 'Heartbeat'"
  echo "in the UI and copy the heartbeat URL into the matching cron job"
  echo "(daily_summary_task / backup script) so silence = page."
fi
